<!DOCTYPE HTML>
<html lang="zh-CN">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <link rel="stylesheet" type="text/css" href="http://img00.zhaopin.cn/2012/css/reset.min.css" media="all">
    <link rel="stylesheet" type="text/css" href="http://my.zhaopin.com/css/new_v5/resume_preview.css" media="all">
	<script language="javascript" type="text/javascript">
	    var _dyweq = _dyweq || [];
	    _dyweq.push(['_setAccount', window['acc4zpAnalytics'] || 'log000001']);
	    _dyweq.push(['_setDomainName', window['dom4zpAnalytics'] || '.zhaopin.com']);
	    if (window['url4zpAnalytics']) _dyweq.push(['_trackPageview', url4zpAnalytics]);
	    else _dyweq.push(['_trackPageview']);
	    (function ()
	    {
	        var dywe = document.createElement('script');
	        dywe.type = 'text/javascript'; dywe.async = true;
	        dywe.src = 'http://img01.zhaopin.cn/2012/js/dywe.js';
	        var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(dywe, s);
	    })();
	    var _gaq = _gaq || [];
	    _gaq.push(['_setAccount', window['acc4googleAnalytics'] || 'UA-7874902-2']);
	    _gaq.push(['_setDomainName', window['dom4googleAnalytics'] || 'zhaopin.com']);
	    _gaq.push(['_addOrganic', 'youdao', 'q']);
	    _gaq.push(['_addOrganic', 'sogou', 'query']);
	    _gaq.push(['_addOrganic', 'soso', 'w']);
	    if (window['url4googleAna']) _gaq.push(['_trackPageview', url4googleAna]);
	    else _gaq.push(['_trackPageview']);
	    (function ()
	    {
	        var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
	        ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
	        var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
	    })();
	    function recordOutboundLink(link, category, action)
	    {
	        function ed(d, a) { var c = encodeURIComponent; return c instanceof Function ? (a ? encodeURI(d) : c(d)) : escape(d); }
	        try
	        {
	            _dywet._getTrackerByName()._trackEvent(category, action);
	            try
	            {
	                _gat._getTrackerByName()._trackEvent(category, action);
	            } catch (err) { }
	            if (link.target != "_blank") setTimeout('document.location = "' + link.href + '"', 100);
	        } catch (err)
	        {
	            var i = new Image(1, 1);
	            var e = document.location;
	            i.src = "http://l.zhaopin.com/track_err.gif?dywee=5(" + category + "*" + action + ")&dywehn=" + ed(e.hostname) + "&dywep=" + ed(e.pathname + e.search, true);
	        }
	    }
</script>
<title>简历预览</title>
</head>
<body>
    <div class="resumeBody">
		<div class="summary">
            <img src="http://img00.zhaopin.cn/2012/img/my/v5/lookResumes.jpg" alt="" width="70" height="90" align="right" class="headerImg" />
            <h1>&#37101;&#28904;&#36713;</h1>
            男 <span class="ver-line" >|</span>
             <span >未婚 <span class="ver-line">|</span></span> 
            1990年4月生 <span class="ver-line">|</span>
            户口：河北张家口 <span class="ver-line">|</span> 
            现居住于北京 <br />
            3年工作经验 | 团员  
            身份证： 13073219900416185X<br />
           <p style="display:none">  </p> 
            <p style="display:none">邮编:</p>
            18513558982 <br />
            E-mail：<a href="mailto:yexuan.guo@gmail.com">yexuan.guo@gmail.com</a> <br />
            <span style="display:none">网站：<a ></a></span>
		</div>
		<dl class="details">
			<dt ><h5>求职意向</h5></dt>
			<dd >
                <ul>
                	<li ><strong>工作性质：</strong>全职</li>
                	<li ><strong>期望职业：</strong>软件研发工程师、互联网软件工程师</li>
                	<li ><strong>期望行业：</strong>计算机软件、IT服务(系统/数据/维护)、互联网/电子商务</li>
                	<li ><strong>工作地区：</strong>北京</li>
                	<li ><strong>期望月薪：</strong>10001-15000元/月</li>
                	<li ><strong>目前状况：</strong>我目前处于离职状态，可立即上岗</li>
                </ul>
            </dd>
			<dt ><h5>自我评价</h5></dt>
			<dd >
                <p style="word-break: break-all; ">掌握PHP面向对象开发,并且有良好的编码规范和编程习惯;熟练使用Memcache啊，redis这些，通常情况下一般常见的技术都OK，常见的PHP框架也都用过，就不一一列举了(因字数有限)，可以写一些前端，只不过兼容性好像差点，JS虽然不是很屌，但是也说的过去，现在PHP框架用的是Yaf，APP接口写过不少，可以进行单独项目开发、有良好的学习与沟通能力、为人诚实谦虚、工作勤奋、认真负责、有耐心。不忌讳加班，但是不希望在没有代码写的情况下耗时间的加班，能跟产品经理良好的沟通，特别特别爱学习新技术~~</p>
            </dd>
			<dt ><h5>工作经历</h5></dt>
			<dd >
            
                <div class="work-experience">
                    <p>2014/08 -- 至今</p>
                    <h6>微博英才(北京)科技发展有限公司 <span class="ver-line" >|</span>  <span class="ver-line" style="display:none">|</span> PHP Developer </h6>
                    <p>
                        <span > 行业类别：互联网/电子商务 <span class="ver-line">|</span> </span>
                        <span >企业性质：民营 <span class="ver-line">|</span> </span>
                        <span > 规模：100-499人 <span class="ver-line">|</span> </span>
                       <span > 职位月薪：10001-15000元/月</span>
                    </p>
                    <p  style="word-break: break-all;" >
                        <strong>工作描述：</strong><br />
                        PHP 项目研发，天天加班写代码！
                    </p>
                   
                </div>
             
                <div class="work-experience">
                    <p>2013/11 -- 2014/08</p>
                    <h6>Tencent(腾讯) <span class="ver-line" >|</span>  <span class="ver-line" style="display:none">|</span> PHP Developer </h6>
                    <p>
                        <span > 行业类别：互联网/电子商务 <span class="ver-line">|</span> </span>
                        <span >企业性质：民营 <span class="ver-line">|</span> </span>
                        <span > 规模：10000人以上 <span class="ver-line">|</span> </span>
                       <span > 职位月薪：8001-10000元/月</span>
                    </p>
                    <p  style="word-break: break-all;" >
                        <strong>工作描述：</strong><br />
                        腾讯精品课开发,http://class.qq.com/&nbsp;&nbsp; 天天加班写代码！
                    </p>
                   
                </div>
             
                <div class="work-experience">
                    <p>2012/08 -- 2013/11</p>
                    <h6>Lowe Profero(睿狮博斐) <span class="ver-line" >|</span>  <span class="ver-line" style="display:none">|</span> PHP Developer </h6>
                    <p>
                        <span > 行业类别：互联网/电子商务 <span class="ver-line">|</span> </span>
                        <span >企业性质：合资 <span class="ver-line">|</span> </span>
                        <span > 规模：500-999人 <span class="ver-line">|</span> </span>
                       <span > 职位月薪：8001-10000元/月</span>
                    </p>
                    <p  style="word-break: break-all;" >
                        <strong>工作描述：</strong><br />
                        写PHP啊，不过从来都不加班。因为这个公司是个做广告的。我们经常没活干！！
                    </p>
                   
                </div>
             
            </dd>
			<dt ><h5>项目经验</h5></dt>
			<dd >
            
                <div class="project-experience">
                    <p>2014/08 -- 2015/02</p>
                    <h6>微人脉(http://renmai.weibo.com)</h6>
                    <div >
                    <p >
                        <strong>软件环境：</strong>Mac OS X + PHP Storm + XAMPP + GIT
                    </p>
                    <p > 
                        <strong>硬件环境：</strong>Linux+Apache+Mysql+PHP
                    </p>
                    <p >
                        <strong>开发工具：</strong>PHP Storm
                    </p>
                    </div>
                    <p >
                        <strong>责任描述：</strong><br />
                     微人脉Web端页面开发！！现在已经上线了，所有在web端看到的页面都是我自个儿做的。
                    </p>
                    <p >
                        <strong>项目简介：</strong><br />
                      独立开发Web&H5页面。PHP运用Yaf框架。前端用的JqueryUI , 独立开发整个项目。
                    </p>
                </div>
              
                <div class="project-experience">
                    <p>2014/08 -- 2015/02</p>
                    <h6>微人脉运营后台</h6>
                    <div >
                    <p >
                        <strong>软件环境：</strong>Mac OS X + PHP Storm + XAMPP + Git
                    </p>
                    <p > 
                        <strong>硬件环境：</strong>Linux+Apache+Mysql+Redis+PHP
                    </p>
                    <p >
                        <strong>开发工具：</strong>PHP Storm
                    </p>
                    </div>
                    <p >
                        <strong>责任描述：</strong><br />
                     负责微人脉运营后台整理开发，运营后台包括，统计，客服，审核，权限管理，财务管理，猎头管理啊些功能，给公司运营组用的。
                    </p>
                    <p >
                        <strong>项目简介：</strong><br />
                      PHP运用Yaf框架。前端用的JqueryUI+Bootstrap , 独立开发整个运营后台。
                    </p>
                </div>
              
                <div class="project-experience">
                    <p>2013/11 -- 2014/08</p>
                    <h6>腾讯精品课(http://class.qq.com)</h6>
                    <div >
                    <p >
                        <strong>软件环境：</strong>Mac OS X
                    </p>
                    <p > 
                        <strong>硬件环境：</strong>Linux+Apache+Mysql+Redis+PHP
                    </p>
                    <p >
                        <strong>开发工具：</strong>MAMP
                    </p>
                    </div>
                    <p >
                        <strong>责任描述：</strong><br />
                     负责腾讯精品课二次改版的，顶部功能用户基本信息和常用连接入口、logo和主要功能入口区域、分类导航区域。页面内导航，课程标示，相关课程，课程回收站，等一些功能开发，常用JS，CSS等修改。
                    </p>
                    <p >
                        <strong>项目简介：</strong><br />
                      精品课是一个增强互动性，方便学习和交流，腾讯教育频道推出腾讯精品课订阅系统，用户可以更好的管理和收藏自己感兴趣的课程、专题培训等，规范整合课程资源。
                    </p>
                </div>
              
                <div class="project-experience">
                    <p>2013/04 -- 2013/11</p>
                    <h6>CNIS(医疗行业OA)</h6>
                    <div >
                    <p >
                        <strong>软件环境：</strong>Mac OS X
                    </p>
                    <p > 
                        <strong>硬件环境：</strong>Linux+Apache+Mysql+PHP
                    </p>
                    <p >
                        <strong>开发工具：</strong>SublimeText
                    </p>
                    </div>
                    <p >
                        <strong>责任描述：</strong><br />
                     项目运用Yii2.0&EXTJS. 常用的YII代码编写.增删改查.EXJ修改等.
                    </p>
                    <p >
                        <strong>项目简介：</strong><br />
                      CNIS,医院营养管理系统.角色主要针对营养师.
                    </p>
                </div>
              
                <div class="project-experience">
                    <p>2012/10 -- 2013/04</p>
                    <h6>Westerunion(西联国际汇款)</h6>
                    <div >
                    <p >
                        <strong>软件环境：</strong>Mac OS X
                    </p>
                    <p > 
                        <strong>硬件环境：</strong>Linux+Apache+Mysql+PHP
                    </p>
                    <p >
                        <strong>开发工具：</strong>SublimeText
                    </p>
                    </div>
                    <p >
                        <strong>责任描述：</strong><br />
                     http://www.westernunion.cn/JP/CN/ID/KR/TH/MY/PH/VN/TW/各语言版本<br/><br/>一些日常BUG的修改.<br/><br/>浏览器兼容性修改.
                    </p>
                    <p >
                        <strong>项目简介：</strong><br />
                       	西联国际汇款公司（Western Union）官网网站，后台运用CMS(EZ)来控制文章发布.页面自适应终端,PC.运用Bootstarp实现.
                    </p>
                </div>
              
                <div class="project-experience">
                    <p>2012/10 -- 2013/06</p>
                    <h6>微信啦(http://weixinla.com)</h6>
                    <div >
                    <p >
                        <strong>软件环境：</strong>Mac OS X + PHP Storm + XAMPP + SVN
                    </p>
                    <p > 
                        <strong>硬件环境：</strong>Linux+Apache+Mysql+PHP
                    </p>
                    <p >
                        <strong>开发工具：</strong>PHP STORM
                    </p>
                    </div>
                    <p >
                        <strong>责任描述：</strong><br />
                     微信公众平台开发~项目用Yii+dedecms写的。
                    </p>
                    <p >
                        <strong>项目简介：</strong><br />
                      项目主要做微信公众账号的建设与认证+微信代运营服务+微信推广营销+微网站建设+企业网站整合营销+微信互推+微信大号推广等服务。
                    </p>
                </div>
              
            </dd>
			<dt ><h5>教育经历</h5></dt>
            
			<dd  [%%show_edu%%]>
                <div class="education-background">
                    <p>2008/09-- 2012/07</p>
                    <h6>北京商贸大学 <span class="ver-line" >|</span> 软件工程 <span class="ver-line"  >|</span> 本科</h6>
                </div>
            </dd>
             
			<dt style="display:none" ><h5>在校学习情况</h5></dt>
            
             <dd>
             <p  style="display:none" ></p>
             </dd>
              
			<dt style="display:none"><h5>在校实践经验</h5></dt>
           
			<dd  style="display:none">
             
            </dd>
			<dt  style="display:none"><h5>培训经历</h5></dt>
			<dd  style="display:none">
             
            </dd>
			<dt style="display:none"><h5>证书</h5></dt>
			<dd style="display:none">
                
            </dd>
			<dt ><h5>语言能力</h5></dt>
			<dd >
                
                <div class="language-skill">
                  英语 <span >：读写能力一般 <span class="ver-line">|</span> 听说能力一般</span>
                </div>
               
            </dd>
			<dt ><h5>专业技能</h5></dt>
			<dd >
             
                <div class="professional-skill">
                    XML<span class="ver-line">|</span>精通 <span class="ver-line">|</span> 36
                </div>
                
                <div class="professional-skill">
                    Linux<span class="ver-line">|</span>精通 <span class="ver-line">|</span> 36
                </div>
                
                <div class="professional-skill">
                    JavaScript<span class="ver-line">|</span>精通 <span class="ver-line">|</span> 36
                </div>
                
                <div class="professional-skill">
                    CSS<span class="ver-line">|</span>精通 <span class="ver-line">|</span> 36
                </div>
                
                <div class="professional-skill">
                    HTML<span class="ver-line">|</span>精通 <span class="ver-line">|</span> 36
                </div>
                
                <div class="professional-skill">
                    PHP<span class="ver-line">|</span>精通 <span class="ver-line">|</span> 36
                </div>
                
            </dd>
            

			<dt style="display:none"><h5>附件</h5></dt>
			<dd style="display:none">
               
            </dd>

            <dt style="display:none"><h5>附件简历</h5></dt>
			<dd style="display:none">
                <div class="photo-attach">
                   <a href=""></a>
                </div>
            </dd>

            <dt style="display:none"><h5>简历内容</h5></dt>
			<dd style="display:none">
                <div class="photo-attach">
                   <p></p>
                </div>
            </dd>
		</dl>
	</div>
</body>
</html>
