<!DOCTYPE html>
<html>
<head lang="en">
  <meta charset="UTF-8">
  <title>iMoooo</title>
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no">
  <meta name="format-detection" content="telephone=no">
  <meta name="renderer" content="webkit">
  <meta http-equiv="Cache-Control" content="no-siteapp" />
  <link rel="alternate icon" type="image/png" href="assets/i/favicon.png">
  <link rel="stylesheet" href="/public/assets/css/amazeui.min.css"/>
  <script src="/public/assets/js/jquery.min.js"></script>
  <style>
    .header {
      text-align: center;
    }
    .header h1 {
      font-size: 200%;
      color: #333;
      margin-top: 30px;
    }
    .header p {
      font-size: 14px;
    }
  </style>
</head>
<body>
<div class="header">
  <div class="am-g">
    <h1>iMoooo</h1>
  </div>
  <hr />
</div>
<div class="am-g">
  <div class="am-u-lg-6 am-u-md-8 am-u-sm-centered">
<!--    <hr>-->
<!--    <div class="am-btn-group">-->
<!--      <a href="#" class="am-btn am-btn-secondary am-btn-sm"><i class="am-icon-github am-icon-sm"></i> Github</a>-->
<!--      <a href="#" class="am-btn am-btn-success am-btn-sm"><i class="am-icon-google-plus-square am-icon-sm"></i> Google+</a>-->
<!--    </div>-->
<!--    <br>-->
<!--    <br>-->

    <form method="post" class="am-form">
      <label for="email">邮箱:</label>
      <input type="email" name="username" id="username" value="">
      <br>
      <label for="password">密码:</label>
      <input type="password" name="password" id="password" value="">
      <br>
      <label for="remember-me">
<!--        <input id="remember-me" type="checkbox">-->
<!--        记住密码-->
      </label>
      <br />
      <div class="am-cf">
        <input type="button" name="" value="登 录" onclick="check();" class="am-btn am-btn-primary am-btn-sm am-fl">
<!--        <input type="submit" name="" value="忘记密码 ^_^? " class="am-btn am-btn-default am-btn-sm am-fr">-->
      </div>
    </form>
    <hr>
    <p>© 2015 Copyright 阿轩和他的朋友们.</p>
  </div>
</div>
</body>
</html>
<script type="application/javascript">
        function check(){
            var username = $("#username").val();
            var password = $("#password").val();
            $.ajax({
                type : 'POST',
                url : '/systemadmin/login',
                data : $.param({
                   username:username,
                   password:password,
                }),
                success : function (data) {
                    if(data == 1){
                        window.location = '/systemadmin/home';
                    }else{
                        alert(data);
                    }
                }
            });
        }
</script>