<!DOCTYPE html>
<html>
<head lang="en">
  <meta charset="UTF-8">
  <title>iMoooo_从0点开始给你一个文艺的iMage生活。</title>
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport"
        content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no">
  <meta name="format-detection" content="telephone=no">
  <meta name="baidu-site-verification" content="DHQKEeqrXh" />
  <meta name="renderer" content="webkit">
  <meta http-equiv="Cache-Control" content="no-siteapp"/>
    <div class="bdsharebuttonbox"><a href="#" class="bds_more" data-cmd="more"></a><a href="#" class="bds_qzone" data-cmd="qzone"></a><a href="#" class="bds_tsina" data-cmd="tsina"></a><a href="#" class="bds_tqq" data-cmd="tqq"></a><a href="#" class="bds_renren" data-cmd="renren"></a><a href="#" class="bds_weixin" data-cmd="weixin"></a></div>
  <link rel="alternate icon" type="image/png" href="assets/i/favicon.png">
  <link rel="stylesheet" href="/public/assets/css/amazeui.min.css"/>
  <style>
    @media only screen and (min-width: 1200px) {
      .blog-g-fixed {
        max-width: 1200px;
      }
    }

    @media only screen and (min-width: 641px) {
      .blog-sidebar {
        font-size: 1.4rem;
      }
    }

    .blog-main {
      padding: 20px 0;
    }

    .blog-title {
      margin: 10px 0 20px 0;
    }

    .blog-meta {
      font-size: 14px;
      margin: 10px 0 20px 0;
      color: #222;
    }

    .blog-meta a {
      color: #27ae60;
    }

    .blog-pagination a {
      font-size: 1.4rem;
    }

    .blog-team li {
      padding: 4px;
    }

    .blog-team img {
      margin-bottom: 0;
    }

    .blog-footer {
      padding: 10px 0;
      text-align: center;
    }
  </style>
</head>
<body>
<header class="am-topbar">
  <h1 class="am-topbar-brand">
    <a href="#">iMoooo</a>
  </h1>

  <button class="am-topbar-btn am-topbar-toggle am-btn am-btn-sm am-btn-success am-show-sm-only"
          data-am-collapse="{target: '#doc-topbar-collapse'}"><span class="am-sr-only">导航切换</span> <span
      class="am-icon-bars"></span></button>

  <div class="am-collapse am-topbar-collapse" id="doc-topbar-collapse">
    <ul class="am-nav am-nav-pills am-topbar-nav">
      <li class="am-active"><a href="#">首页</a></li>
<!--      <li><a href="#">搜索还没实现</a></li>-->
<!--      <li class="am-dropdown" data-am-dropdown>-->
<!--        <a class="am-dropdown-toggle" data-am-dropdown-toggle href="javascript:;">-->
<!--          菜单 <span class="am-icon-caret-down"></span>-->
<!--        </a>-->
<!--        <ul class="am-dropdown-content">-->
<!--          <li class="am-dropdown-header">标题</li>-->
<!--          <li><a href="#">关于我，下面自己看。</a></li>-->
<!--          <li><a href="#">往下面翻！</a></li>-->
<!--        </ul>-->
<!--      </li>-->
    </ul>

    <form class="am-topbar-form am-topbar-left am-form-inline am-topbar-right" role="search">
<!--      <div class="am-form-group">-->
<!--        <input type="text" class="am-form-field am-input-sm" placeholder="搜索文章">-->
<!--      </div>-->
<!--      <button type="submit" class="am-btn am-btn-default am-btn-sm">搜索</button>-->
    </form>

  </div>
</header>

<div class="am-g am-g-fixed blog-g-fixed">
  <div class="am-u-md-8">
      <article class="blog-main">
          <h3 class="am-article-title">
              <a href="#">未来的财富不是属于有钱人，更不属于没钱人，是属于正能量的人！</a>
          </h3>
          <h4 class="am-article-meta blog-meta">by <a href="">郭蜜桃。</a>2015年06月04日17:12:36</h4>
          </h4>
          <div class="am-g blog-content">
              <div class="am-u-lg-7">
                  <p>
                      不要跟消耗你的人在一起，去爱一个给你正能量的人。

                      每个人的生活都一样，细看是碎片，远看是长河的时间中寻找着幸福，寻找着能够让自己幸福的一切事物：物质、荣誉、成就。

                      既然你想幸福，就去找一个能够让你感到幸福的人吧。

                      不要找一个没有激情、没有好奇心的人过日子，他们只会和你窝在家里唉声叹气抱怨生活真没劲，只会打开电视，翻来覆去的调转频道，好像除了看电视再也想不出其它的娱乐项目。

                      拥有正面能量的人，对很多事情充满好奇，无论遇到什么样的新鲜事物都想尝试一下，会带你去尝试一家新的餐厅，带你去看一场口碑不错的电影，带你去体验新推出的娱乐节目，带你去下一个陌生的城市旅行。

                      你会发现世界很大，值得用尽一生去不断尝试。

                      不要找一个没有安全感的人过日子，他们一直在排查可能的不幸，和焦虑未来的灾难。他们一直在想该怎么办。

                      拥有正面能量的人，会对生活乐观，对自己信任，他们知道生活本来就悲喜交加，所以已经学会坦然面对。

                      当烦扰来袭时，就理性解决。他们相信人定胜天，确实无法获胜时，就坦然接受。

                      他们能够正确认识自己，有自知之明，不会自我贬损也不会自我膨胀，他们在该独立的时候独立，该求助的时候求助。

                      拥有正面能量的人，拥有大智慧，他们分得清世界的黑白曲直，不会在人生的道路上跑偏，也不会随波逐流。

                      不会夸大事情的不利面。他们知道世界运作的原理，明白人人都有阴晴阳缺。他们在你需要时给你最中肯的建议，有原则却又求新求变，有主见却又听得进劝。

                      不要找一个容易放弃的人过日子。他们没有信仰，也没有梦想。他们遇到挫折的第一反应和最终反应都是逃避，他们可以放弃整个世界。

                      拥有正面能量的人，坚定自己的信念，拥有人生的目标，知道自己的所需并为之不断努力。他们欢迎变化也制造进步。

                      当困难来临，他们不嫌麻烦或贪图安逸，他们知道山丘后面会有道更美丽的风景。

                      是的,去爱一个拥有正面能量的人吧。他们会给你惊喜，同时也会带给你感悟。他们让你把路走直，戒断所有扭曲的价值观。

                      如果你本身就不是一个拥有足够正面能量的人，那么就请你一定要爱一个拥有正面能量的人。

                      在这道数学题里，负负并不能得正，另一个同样具有负面能量的人会把你的人生拖垮，让具有正面能量的人导正你的灵魂和行为吧，潜移默化中，你会变得更加开朗和幸福。

                      这一定比任何财富更能长久的滋养你的心灵!

                      人生是一个选择的过程，人生最重要的选择，就是选择和谁在一起。

                      选择和谁共事，选择和谁交朋友，选择和谁结婚，选择向谁学习......

                      你和谁在一起，决定着你的未来。
                      你和谁在一起，全由你的选择决定。

                      马云说：一根稻草丟在大街上是垃圾，绑在大白菜上可以卖白菜的价格，绑在大闸蟹上就是大闸蟹的价格。所以21世纪看你与谁捆绑在一起。

                      “在一起”三个字决定人的命运，亲贤臣、远小人。

                      永远和智慧、积极、阳光、有责任感、不畏困难、勇于挑战的人、充满正能量的人在一起。你就成功一半了。
                  </p>
              </div>
              <div class="am-u-lg-5">
<!--                  <p><img src="/public/images/1.jpeg"></p>-->
              </div>
          </div>
<!--          <div class="am-g">-->
<!--              <div class="am-u-sm-12">-->
<!--                  <p>尼玛H5的标签好强大啊。。。。</p>-->
<!--              </div>-->
<!--          </div>-->
      </article>



<!--    <hr class="am-article-divider blog-hr">-->
<!--    <ul class="am-pagination blog-pagination">-->
<!--      <li class="am-pagination-prev"><a href="">&laquo; 上一页</a></li>-->
<!--      <li class="am-pagination-next"><a href="">下一页 &raquo;</a></li>-->
<!--    </ul>-->
  </div>

  <div class="am-u-md-4 blog-sidebar">
    <div class="am-panel-group">
<!--      <section class="am-panel am-panel-default">-->
<!--        <div class="am-panel-hd">关于我</div>-->
<!--        <div class="am-panel-bd">-->
<!--          <p>-->
<!--               iMoooo创始人！！！二逼PHP码农一枚！PS：说创始人的时候好羞射啊。。。啊哈哈哈哈哈。-->
<!--          </p>-->
<!--          <a class="am-btn am-btn-success am-btn-sm" href="#">查看更多 →</a>-->
<!--        </div>-->
<!--      </section>-->
<!--      <section class="am-panel am-panel-default">-->
<!--        <div class="am-panel-hd">文章目录</div>-->
<!--        <ul class="am-list blog-list">-->
<!--          <li><a href="#">测试标题1</a></li>-->
<!--        </ul>-->
<!--      </section>-->
<!---->
<!--      <section class="am-panel am-panel-default">-->
<!--        <div class="am-panel-hd">团队成员</div>-->
<!--        <div class="am-panel-bd">-->
<!--          <ul class="am-avg-sm-4 blog-team">-->
<!--            <li><img class="am-thumbnail" src="/public/images/touxiang.JPG" alt=""/>-->
<!--            </li>-->
<!--          </ul>-->
<!--        </div>-->
<!--      </section>-->
    </div>
  </div>

</div>

<footer class="blog-footer">
  <p>
    <small>© Copyright 阿轩和他的朋友们.</small>
  </p>
</footer>
<!--[if lt IE 9]>
<script src="http://libs.baidu.com/jquery/1.11.1/jquery.min.js"></script>
<script src="http://cdn.staticfile.org/modernizr/2.8.3/modernizr.js"></script>
<script src="/public/assets/js/polyfill/rem.min.js"></script>
<script src="/public/assets/js/polyfill/respond.min.js"></script>
<script src="/punlic/assets/js/amazeui.legacy.js"></script>
<![endif]-->
<!--[if (gte IE 9)|!(IE)]><!-->
<script src="/public/assets/js/jquery.min.js"></script>
<script src="/public/assets/js/amazeui.min.js"></script>
<!--<![endif]-->
</body>
</html>